### ISSUE TITLE
 Contract deploy method should support Vec<u8>

### ISSUE THREAD

**Issue by jeremymj** [polkadot-js/api#1549]
I get an error `main.749f3709.js:21450 Uncaught Error: createType({ "elems": "Vec" }):: Unable to find plain type for {"info":6,"type":"Vec"}`, when I call deploy at https://polkadot.js.org/apps/#/contracts/code.
![sALNPfuHKHgwCxEqXIRgdfDM](https://user-images.githubusercontent.com/13585788/68310368-d985e700-00ea-11ea-8d9e-c8783e277fb4.png)
 When I remove Vec<u8> in deploy, the contract can be instantiated normally.

**Comment by jacogr** [comment]
Can you please supply the ABI?

**Comment by jeremymj** [comment]
I tested it with this [ABI](https://github.com/polkadot-js/api/files/3817509/abi.txt).I did more tests on this version `ec00ab9639fa8dd94d16f156c8bcfb1fa93a76bb` [app](https://github.com/polkadot-js/apps) and found that the contract method contained `Vec<u8>` could not be called normally.

**Comment by jacogr** [comment]
This should be addressed in the API after https://github.com/polkadot-js/api/pull/1591 (so should be available on a latest beta). However, the UI does not support it yet since the relevant UI PR needed to be reverted since it broke transactions -https://github.com/polkadot-js/apps/pull/1916

**Comment by jeremymj** [comment]
@jacogr  I use `polkadot js 0.97.0-beta.23` version and the following code
```js
  const encode_deploy_data = "0x0c58186e5360509b10c7cff6adee9b987c5e72e1ef6f2c9ad8b5ee0776e4aefb0b186a6572656d7900d3f2a566990cf060555ffe9a450d936319ea36661f31ce6b4416ca78d041b9c5186a6572656d79009ca148e45a24fc649c3b14bb1dd4c22f13dc3a05920138a964398dae52296d40186a6572656d7900";
  const encode_deploy_array = hexToU8a(encode_deploy_data);
  const fn_data = abi.constructors[0](encode_deploy_array,100,10);
```
found that the problem still exists.

**Comment by jacogr** [comment]
@jeremymj Thanks for bearing with us... trying to get this sorted.

@kwingram25 Could you please take a look at this one - this is latest, and should be fixed in the API itself.

**Comment by kwingram25** [comment]
Can you provide the WASM also? @jeremymj

**Comment by jeremymj** [comment]
@kwingram25 The files I tested were as follows:[app.wasm](https://github.com/polkadot-js/api/files/3894798/app.txt),[metadata.json](https://github.com/polkadot-js/api/files/3894799/metadata.txt),Call js api by the following way.
```js
import { Abi, } from '@polkadot/api-contract';
import { stringToU8a,} from '@polkadot/util';
import { ApiPromise } from '@polkadot/api';
import {Keyring} from '@polkadot/keyring';
import * as metadata from "../metadata.json";
import { TypeRegistry } from '@polkadot/types';

const app = (<any>metadata);
const abi = getAbiObj(app);
new ApiPromise().isReady.then((api) => {
    const keyring = new Keyring({type: 'sr25519'});
    const alice = keyring.addFromUri('//Alice');
    contract_instantiate(api, abi, alice);
}).catch(console.error).finally(() => process.exit());

function contract_instantiate(api, abi, account) {
    const fn_data = abi.constructors[0]( stringToU8a("test"),true);
    const instantiate_data = api.tx.contracts.instantiate(10000000, 500000, "0xee0fd5c108a6a2eb1721f5031ab23e139dd108b0ad799104592dab413e6379f4", fn_data);
    console.log("instantiate_data:" + instantiate_data);
    const signed_data = instantiate_data.sign(account);
    console.log("signed data is:" + signed_data);
}
function getAbiObj(obj) {
    const registry = new TypeRegistry();
    const contractAbi = new Abi(registry,obj);
    return contractAbi
}
```
 I get this error `Error: Unable to find plain type for {"info":6,"type":"Vec"}` when I run，

**Comment by iorveth** [comment]
Hello, i have the same issue, any updates here?

**Comment by jacogr** [comment]
No updates, it is also one of the hanging issues for https://github.com/polkadot-js/api/pull/1662
