### ISSUE TITLE
FATAL: Unable to initialize @polkadot/wasm-crypto:: WebAssembly is not available in your environment

### ISSUE THREAD

**Issue by giga-mind** [polkadot-js/api#4704]
Trying to init the polkadot api in a fresh react-native app and getting the following error.

`
ERROR  FATAL: Unable to initialize @polkadot/wasm-crypto:: WebAssembly is not available in your environment
API/INIT: [Error: FATAL: Unable to initialize the API: The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.]
`

Also using `import '@polkadot/wasm-crypto/initWasmAsm'; ` at the top level

Version:
"@polkadot/api": "^7.14.3",

**Comment by jacogr** [comment]
See this discussion - https://github.com/polkadot-js/wasm/issues/315

**Comment by giga-mind** [comment]
@jacogr 

```
async function _onProviderConnect2() {
  this._isConnected.next(true);

  this.emit('connected');

  try {
    const [hasMeta, cryptoReady] = await Promise.all([this._loadMeta(), this._options.initWasm === false ? Promise.resolve(true) : cryptoWaitReady()]);

    this._subscribeHealth();

    if (hasMeta && !this._isReady && cryptoReady) {
      this._isReady = true;
      this.emit('ready', this);
    }
  } catch (_error) {
    const error = new Error(`FATAL: Unable to initialize the API: ${_error.message}`);
    l.error(error);
    this.emit('error', error);
  }
}
```

Here the `this._loadMeta()` call is failing with the following message.

`[Error: The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.]`

**Comment by jacogr** [comment]
The above sounds like an issue with the `cryptoWaitReady()` not being very lazy. Will investigate and put in a fix.

As a temp work-around until it is patched and released (over the weekend), this should do the trick -

```js
import { cryptoWaitReady } from '@polkadot/util-crypto';

...
// do this first
await cryptoWaitReady();

// then init API
const api = new ApiPromise.create({ ... });
```

**Comment by Thinhnguyen185** [comment]
I'm using @polkadot/api lastest, IOS build success, Android Error with above error 
 ERROR  FATAL: Unable to initialize @polkadot/wasm-crypto:: WebAssembly is not available in your environment

**Comment by kamaci** [comment]
@jacogr that temp work-around doesn't work.

**Comment by kamaci** [comment]
I get this error when I use:

`new Keyring({type: 'sr25519', ss58Format: 2})`

However, it doesn't throw error for that:

`new Keyring({ss58Format: 2})`

**Comment by truchq-ibl** [comment]
@jacogr : I got the same error as @Thinhnguyen185 , please,  help me to solve it.
step: 
- init project react-native@0.63.3
- install @polkadot/api@8.0.2
- import lib in App.js 
import { ApiPromise } from '@polkadot/api';
- run :  react-native run-android
- Error
The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.

**Comment by Thinhnguyen185** [comment]
@truchq-ibl i resolve error with new project RN 0.67.4
In Index.js
import '@polkadot/wasm-crypto/initOnlyAsm';
Done

**Comment by truchq-ibl** [comment]
@Thinhnguyen185 Many thanks. But the error is still the same.
FATAL: Unable to initialize @polkadot/wasm-crypto:: Can't find variable: WebAssembly 
package.json
`{
  "name": "testlib0674",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@polkadot/api": "^8.0.2",
    "react": "17.0.2",
    "react-native": "0.67.4"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
`
index.js
`/**
 * @format
 */
import '@polkadot/wasm-crypto/initOnlyAsm';
import { AppRegistry } from 'react-native';
import App from './App';
import { name as appName } from './app.json';

AppRegistry.registerComponent(appName, () => App);
`
App.js
`import React, { useEffect } from 'react';

import { waitReady, bip39Generate } from '@polkadot/wasm-crypto';
const App: () => React$Node = () => {
  useEffect(() => {
    waitReady()
      .then(() => {
        const passphrase = bip39Generate(12)
        console.log('passphrase', passphrase);
      })
      .catch((error) => {
        console.log('error', error);
      });
  }, [])

  return (
    <>
    </>
  );
};
export default App;
`
Error: 
FATAL: Unable to initialize @polkadot/wasm-crypto:: WebAssembly is not available in your environment 
error [Error: The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.]

Can you tell me what's missing?
@Thinhnguyen185

**Comment by Thinhnguyen185** [comment]
@truchq-ibl  you can config same u, you can use another version 
`
"@polkadot/api": "7.15.1",
 "@polkadot/util-crypto": "8.7.1",
 "@polkadot/wasm-crypto": "^5.1.1",   
`
This is version polkadotjs I used in my project

**Comment by truchq-ibl** [comment]
@Thinhnguyen185 : 
I installed the libs by your version and the error still occurs.
Does your project have a package that supports wasm ?  If you don't mind, can I have your contact?
